export const FETCH_TICKETS_STATUS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_STATUS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_STATUS_FAILURE = "FETCH_TICKETS_FAILURE";
