export const UPDATE_CUSTOMER_DETAILS_REQUEST = "UPDATE_CUSTOMER_DETAILS_REQUEST";
export const UPDATE_CUSTOMER_DETAILS_SUCCESS = "UPDATE_CUSTOMER_DETAILS_SUCCESS";
export const UPDATE_CUSTOMER_DETAILS_FAILURE = "UPDATE_CUSTOMER_DETAILS_FAILURE";
export const RESET_UPDATE_CUSTOMER_DETAILS = "RESET_UPDATE_CUSTOMER_DETAILS";
