// addEmployeeType.js
export const FETCH_ADD_EMPLOYEE_STATUS_REQUEST = "FETCH_ADD_EMPLOYEE_REQUEST";
export const FETCH_ADD_EMPLOYEE_STATUS_SUCCESS = "FETCH_ADD_EMPLOYEE_SUCCESS";
export const FETCH_ADD_EMPLOYEE_STATUS_FAILURE = "FETCH_ADD_EMPLOYEE_FAILURE";
