export const FETCH_DELETE_EMPLOYEE_STATUS_REQUEST = "FETCH_DELETE_EMPLOYEE_REQUEST";
export const FETCH_DELETE_EMPLOYEE_STATUS_SUCCESS = "FETCH_DELETE_EMPLOYEE_SUCCESS";
export const FETCH_DELETE_EMPLOYEE_STATUS_FAILURE = "FETCH_DELETE_EMPLOYEE_FAILURE";
