export const FETCH_UPDATE_EMPLOYEE_REQUEST = "FETCH_UPDATE_EMPLOYEE_REQUEST";
export const FETCH_UPDATE_EMPLOYEE_SUCCESS = "FETCH_UPDATE_EMPLOYEE_SUCCESS";
export const FETCH_UPDATE_EMPLOYEE_FAILURE = "FETCH_UPDATE_EMPLOYEE_FAILURE";
