@baseURL = https://localhost:6000/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDE1NDkzOCwiZXhwIjoxNzQwMTU4NTM4LCJjbGFpbXMiOnsibmFtZSI6IlNwb29ydGhpIEcgUyIsImVtYWlsIjoic3Bvb3J0aGlAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwidXNlck5hbWUiOiJzcG9vcnRoaS1ncyJ9fQ.WWoDs4mZmElnJ8XeHz3Ct0h5uSvAtYD83gSpLIOOfnFs2AAraVyqAZt54bqV4YLLPAMwVO1UyBrlteunbHP7cCgDDo5B-pn5a_vh-HI-dPd_wydEP3nB_mpjD1QT9BL2lpOUQpCdMf_NeuX7Yube-gE6JpYx1Ju88p6Z_KrZ24DIXJc2cAQ_9PoooaL0PqDsmQJUTk4wVCL8SHxNeBBvsEX7ElHcQ8V2xV5CWFvmDjtKSH1PALGuqVEd2BYTZ9_I--k5rCZ7BWpyjSReEnPZLiZjy7DXVf3wa-jDbq9MxGEwvE7Dfw9dWdqK-VKNl_dUTgrfBU9sTfmbbvipNUWb_Q

### GET all employees
GET {{baseURL}}/employees

### GET an employee by ID
GET {{baseURL}}/employees/EMP002

### GET an employee with INVALID ID
GET {{baseURL}}/employees/INVALID_ID

### POST a new employee
POST {{baseURL}}/employees
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "name": "Guru Pruthvi",
    "managerId": "nirmala",
    "designation": "Software Engineer",
    "department": "Engineering",
    "email": "gurupruthvi61@gmail.com",
    "phoneNo": "9019867898",
    "password": "hashedpassword123"
}




### POST a new Different Employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "EMPLOYEE_ID": "EMP002",
    "EMPLOYEE_MANAGERID": "MGR001",
    "EMPLOYEE_FIRSTNAME": "Jane",
    "EMPLOYEE_LASTNAME": "Smith",
    "EMPLOYEE_DESIGNATION": "Project Manager",
    "EMPLOYEE_DEPARTMENT": "Operations",
    "EMPLOYEE_GENDER": "FEMALE",
    "EMPLOYEE_DATEOFBIRTH": "1985-08-22",
    "EMPLOYEE_DATEOFJOINING": "2018-06-12",
    "EMPLOYEE_TAKEHOME": 70000,
    "EMPLOYEE_EMAIL": "jane.smith@example.com",
    "EMPLOYEE_PHONENO": "9988776655",
    "EMPLOYEE_PASSWORD": "securePassword456"
}


### Delete the employee by ID
DELETE {{baseURL}}/employees/EMP002

### PUT to update the employee Details
PUT {{baseURL}}/employees/EMP001
Content-Type: application/json

{
    "EMPLOYEE_TAKEHOME": 60000
}
