export const FETCH_TICKETS_COUNT_REQUEST = "FETCH_TICKETS_COUNT_REQUEST";
export const FETCH_TICKETS_COUNT_SUCCESS = "FETCH_TICKETS_COUNT_SUCCESS";
export const FETCH_TICKETS_COUNT_FAILURE = "FETCH_TICKETS_COUNT_FAILURE";
