export const FETCH_EMPLOYEE_DETAILS_REQUEST = "FETCH_EMPLOYEE_DETAILS_REQUEST";
export const FETCH_EMPLOYEE_DETAILS_SUCCESS = "FETCH_EMPLOYEE_DETAILS_SUCCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";
