export const UPDATE_EMPLOYEE_DETAILS_REQUEST = "UPDATE_EMPLOYEE_DETAILS_REQUEST";
export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DETAILS_FAILURE";
export const RESET_UPDATE_EMPLOYEE_DETAILS = "RESET_UPDATE_EMPLOYEE_DETAILS";
