@baseURL = https://localhost:5000/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDM2MzQ2MiwiZXhwIjoxNzQwMzY3MDYyLCJjbGFpbXMiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsibWFuYWdlciJdLCJ1c2VyTmFtZSI6ImpvaG5kb2UifX0.J5Ldi9Fz3wqh1UG1C4EM6nv_0mBDiCpnFNW4c_i8AOzYPs9hg2_1dq3p4Qs-Z7m01mg7MQNM2ZZxOfBawwJEIFx7GFan5HaFwnRdHA9VXJhcS1XoPu8fDPzHfHk59IL04IT9wdSVs_senamfPkfLYbrVdguDVAyN8UO7wnx33VdVXvaD8X0DIJ3zVP8ZcMMjYIlEnB8b0592QeNXtyfq1Pq-Kuoc80SZPRnFuOWsISRBQX3j8gmh5t3MKzHI6pZjypS_qlqJXT6v_F-f6xq2YwjpJlcViR7127tAithuKwOHzkvXIE1xcsDyY48xn7AChWTCGVLjX1GKiaMBg0r_dg

###GET all managers
GET {{baseURL}}/managers
Authorization: BEARER {{token}}

### GET a manager by ID
GET {{baseURL}}/managers/mgr12345

###GET a manager with INVALID ID
GET {{baseURL}}/managers/INVALID_ID

### GET Specified ManagerId ticketStatus
GET {{baseURL}}/managers/johndoe/ticketStatus
Authorization: BEARER {{token}}

### GET Specified ManagerId stats

GET {{baseURL}}/managers/johndoe/stats
Authorization: BEARER {{token}}



### Get Specified TicketStatus of specified Manager
GET {{baseURL}}/managers/johndoe/ticketStatus/open
Authorization: BEARER {{token}}

### Get Specified TicketStatus of specified Manager with specified ticketId
GET {{baseURL}}/managers/guru_pruthvi/ticketStatus/pending/TICKET567

### Get the specified Manager ticket count of their collegues

GET {{baseURL}}/managers/johndoe/collegue/ticketCount
Authorization: BEARER {{token}}


### GET all Employee under manager
GET {{baseURL}}/managers/johndoe/collegue
Authorization: BEARER {{token}}

### GET specific Employee under manager
GET {{baseURL}}/managers/guru_pruthvi/collegue/nirmala
Authorization: BEARER {{token}}

### POST a new manager
POST {{baseURL}}/managers
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "securePass123",
    "username": "guru prasad",
    "phone_Number": "9886828769",
    "name": "Guru Prasad",
    "department": "operation"
}

### POST a new manager
POST {{baseURL}}/managers 
Content-Type: application/json

{
    "Manager_ID": "manager-102",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}


###Delete the manager by id
DELETE {{baseURL}}/managers/mgr12345

###PUT to update the manager Details
PUT {{baseURL}}/managers/mgr12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "domain": "operations"
}
