export const FETCH_MANAGER_DETAILS_REQUEST = "FETCH_MANAGER_DETAILS_REQUEST";
export const FETCH_MANAGER_DETAILS_SUCCESS = "FETCH_MANAGER_DETAILS_SUCCESS";
export const FETCH_MANAGER_DETAILS_FAILURE = "FETCH_MANAGER_DETAILS_FAILURE";