export const UPDATE_MANAGER_DETAILS_REQUEST = "UPDATE_MANAGER_DETAILS_REQUEST";
export const UPDATE_MANAGER_DETAILS_SUCCESS = "UPDATE_MANAGER_DETAILS_SUCCESS";
export const UPDATE_MANAGER_DETAILS_FAILURE = "UPDATE_MANAGER_DETAILS_FAILURE";
export const RESET_UPDATE_MANAGER_DETAILS = "RESET_UPDATE_MANAGER_DETAILS";
