export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
export const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";
export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";
export const OTP_RESET = "OTP_RESET";
